# Generated by Django 4.1.10 on 2024-04-06 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip_planning", "0004_tripplanning_like"),
    ]

    operations = []
